# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               madhavrao
tagline:             '   ...in search of noesis'
description:         'Space, to share my personal experiences with technology and productivity experiments'
url:                 http://www.zen-noesis.in
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Madhavrao Pachupate
  url:               https://twitter.com/madhavraop
  email:             madhavraop@outlook.com

